apiVersion: v1
kind: Service
metadata:
  name: hello-k3s-svc
spec:
  type: NodePort
  selector:
    app: hello-k3s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
